[versions]
brave-instrumentation = '5.15.0'
brave-opentracing = '1.0.0'
jaeger = '1.8.1'
kotlin = '1.8.10'
kotlin-coroutines = '1.6.4'
opentracing = '0.33.0'
zipkin-reporter = '2.16.3'

[libraries]
brave-opentracing = { module = 'io.opentracing.brave:brave-opentracing', version.ref = 'brave-opentracing' }
jaeger = { module = 'io.jaegertracing:jaeger-thrift', version.ref = 'jaeger' }
kotlinx-coroutines-core = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-core', version.ref = 'kotlin-coroutines' }
kotlinx-coroutines-reactor = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-reactor', version.ref = 'kotlin-coroutines' }
opentracing = { module = 'io.opentracing:opentracing-api', version.ref = 'opentracing' }
opentracing-util = { module = 'io.opentracing:opentracing-util', version.ref = 'opentracing' }
zipkin-brave-instrumentation = { module = 'io.zipkin.brave:brave-instrumentation-http', version.ref = 'brave-instrumentation' }
zipkin-reporter = { module = 'io.zipkin.reporter2:zipkin-reporter', version.ref = 'zipkin-reporter' }

[plugins]
kotlin = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }
